-- Timer mutations may be retried by a browser after a network timeout. Keep a
-- durable receipt so a retry returns the original result instead of creating
-- another work session or adding the same minutes twice.
create table if not exists public.task_timer_operation_receipts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  operation_key text not null,
  operation text not null,
  response jsonb not null,
  created_at timestamptz not null default now(),
  constraint task_timer_operation_receipts_key_check check (length(operation_key) between 8 and 160),
  constraint task_timer_operation_receipts_operation_check check (operation in ('add_time', 'log_work'))
);

create unique index if not exists task_timer_operation_receipts_user_key_idx
  on public.task_timer_operation_receipts (user_id, operation_key);

create index if not exists task_timer_operation_receipts_created_idx
  on public.task_timer_operation_receipts (user_id, created_at desc);

alter table public.task_timer_operation_receipts enable row level security;
revoke all on public.task_timer_operation_receipts from anon, authenticated;
grant select, insert on public.task_timer_operation_receipts to service_role;
grant usage, select on sequence public.task_timer_operation_receipts_id_seq to service_role;

-- Work history is an audit trail. Keep it when a task is deleted instead of
-- cascading it away; the task id remains as the historical identity.
alter table public.task_work_sessions
  drop constraint if exists task_work_sessions_task_fk;

-- Deleting a task must never cascade away a live timer. The UI stops the timer
-- first, while this database guard covers deletes from another device or API.
create or replace function public.reject_task_delete_with_running_timer()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if exists (
    select 1
    from public.task_work_sessions s
    where s.user_id = old.user_id
      and s.task_id = old.id
      and s.state = 'running'
  ) then
    raise exception using
      errcode = '23514',
      message = 'Cannot delete a task with a running timer.';
  end if;
  return old;
end;
$$;

drop trigger if exists tasks_reject_running_timer_delete on public.tasks;
create trigger tasks_reject_running_timer_delete
before delete on public.tasks
for each row execute function public.reject_task_delete_with_running_timer();

revoke all on function public.reject_task_delete_with_running_timer() from public, anon, authenticated;
grant execute on function public.reject_task_delete_with_running_timer() to service_role;
