create table if not exists public.task_schedule_cleanup (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  calendar_id text not null,
  provider_event_id text not null,
  created_at timestamptz not null default now(),
  processed_at timestamptz,
  last_error text
);

create index if not exists task_schedule_cleanup_pending_idx
  on public.task_schedule_cleanup (user_id, processed_at, created_at);

alter table public.task_schedule_cleanup enable row level security;
revoke all on public.task_schedule_cleanup from authenticated;

create or replace function public.capture_task_schedule_cleanup()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.task_schedule_cleanup (user_id, calendar_id, provider_event_id)
  select b.user_id, b.calendar_id, b.provider_event_id
  from public.task_schedule_blocks b
  where b.user_id = old.user_id
    and b.task_id = old.id
    and b.provider_event_id is not null
    and b.state in ('flexible', 'locked')
    and b.end_at > now();
  return old;
end;
$$;

drop trigger if exists tasks_capture_schedule_cleanup on public.tasks;
create trigger tasks_capture_schedule_cleanup
before delete on public.tasks
for each row execute function public.capture_task_schedule_cleanup();
